### ISSUE TITLE
Scss files with multiple transition-property values are improperly minimized

### ISSUE THREAD

**Issue by wclaibor** [ng-packagr/ng-packagr#1607]
## Type of Issue

```
[ x] Bug Report
[ ] Feature Request
```

## Description

There is a bug in clean-css (https://github.com/jakubpawlowicz/clean-css/issues/1115) that incorrectly minifies transitions with multiple transition-property values into a single transition-property. Since ng-packagr uses clean-css at level 2, this bug is present in libraries that use ng-packagr to build.

#### How To Reproduce

Add the following properties to a selector in a scss file

```css
foo { transition-property: transform, margin-left;
  transition-delay: 0ms;
  transition-duration: 375ms;
  transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
}
```
See my fork for failing integration tests

https://github.com/wclaibor/ng-packagr

Tests fail when you run these commands

```bash
yarn
yarn build
yarn integration:samples
yarn integration:specs
```

#### Expected Behaviour

Expected css output

```css
foo{transition-property: transform, margin-left; transition-delay: 0ms;transition-duration: 375ms;transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);}
```

actual css output 

```css
foo{transition:transform 375ms cubic-bezier(.4,0,.2,1)}
```

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 9.1.1
@angular/*: 9.2.1
typescript: 3.8.3
rxjs: 6.5.5
node: 12.13.0
yarn: 1.22.4
```

**Comment by alan-agius4** [comment]
Hi @wclaibor, 

Will be replacing the css optimizer in the next major version. For the time being I suggest you mark the problematic CSS block with special comments to make clean-css ignore it

```css
/* clean-css ignore:start */
foo{transition-property: transform, margin-left; transition-delay: 0ms;transition-duration: 375ms;transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);}
/* clean-css ignore:end */
```
